[package]
name = "ascendancy_macros"
description = "Macros for a bevy game"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["jjkirkpatrick"]

[lib]
proc-macro = true

[dependencies]
syn = "2.0.50"
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.1.0"